### ISSUE TITLE
small int overflow reading serial number on SHT41 Trinkey

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/Adafruit_CircuitPython_SHT4x#13]
I'm trying the example code on an SHT41 Trinkey running CircuitPython 9.0.3 and the line 12 in code.py throws this error:
```
 File "code.py", line 12, in <module>
  File "adafruit_sht4x.py", line 159, in serial_number

OverflowError: small int overflow
```

**Comment by caternuson** [comment]
That'll be a limit of the CP build for that board.

The serial number isn't really needed for anything. Can try commenting out that line.

**Comment by jedgarpark** [comment]
Thanks, @caternuson yes, i don't really need that line in the demo and commented it out.
