### ISSUE TITLE
NEWMODE value is printed in "sht.mode = adafruit_sht4x.Mode.MODE" call

### ISSUE THREAD

**Issue by pklosko** [adafruit/Adafruit_CircuitPython_SHT4x#6]
Solution:
Comment print(new_mode), line 168,  in
 
def mode(self, new_mode):
        print(new_mode)
        if not Mode.is_valid(new_mode):
            raise AttributeError("mode must be a Mode")
        self._mode = new_mode

**Comment by jposada202020** [comment]
Thanks @pklosko corrected by #7
