### ISSUE TITLE
Documenting if and if yes how to change the address

### ISSUE THREAD

**Issue by viktoriasee** [adafruit/Adafruit_CircuitPython_SHT4x#8]
It is not clear from the Adafruit documentation right now whether one can change the i2c address in order to use two sensor boards at once. It is clear from the Sensirion documentation that there is no hardware solution to change the address like the older SHT3x had.

**Comment by jposada202020** [comment]
Yes I think you are right, but normally we document the features of a certain device. could be very difficult to document  what is not featured.
Could you point me in the right direction in the datasheet, I was reviewing the datasheet and I could not find the reference that you mentioned, the closes was that depending on the model the device address is different.

Thanks.

**Comment by viktoriasee** [comment]
I am talking about the Adafruit 4885 which basically is an evalboard of the Sensirion SHT40. [The reference in the datasheet of the Sensirion SHT3x](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT3x_Datasheet_digital.pdf#page=8) is on page 8: You see there is a dedicated leg on the hardware.

The SHT4x does not come with this feature, see [p. 13 of the datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT4x_Datasheet.pdf#page=13).

**Comment by jposada202020** [comment]
Understood. I got the idea with the datasheet. You would like a note in the documentation that specifies that for the SHT4x you could not setup the address. If does not hurt to have it, that clarifies things for folks hat works with both type of sensors.  would you want to make a PR to modify the documentation?
Thanks

**Comment by viktoriasee** [comment]
Well it is one detail to state in the doc that there is no integrated hardware solution to change the address. But is it possible to change the address in software? How? I did not read the entire [NXP I2C bus specification](https://www.nxp.com/docs/en/user-guide/UM10204.pdf).
For such an evalboard I would consider a dip switch or a soldering bridge most userfriendly to select an address.

**Comment by ladyada** [comment]
added a note here
https://learn.adafruit.com/adafruit-sht40-temperature-humidity-sensor/pinouts
it is not possible

**Comment by viktoriasee** [comment]
That is an improvement. Even better would be to mention that Adafruit offers hardware solutions to that problem such as the [Adafruit TCA9548A 1-to-8 I2C Multiplexer Breakout](https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/overview)
